package model;

public enum RequestType {
    BUY_ANIMAL, PICKUP, CAGE, PLANT, WELL, START,
    UPGRADE_WORKSHOP, UPGRADE_CAT, UPGRADE_WELL, UPGRADE_VEHICLE, UPGRADE_WAREHOUSE,
    LOAD_CUSTOM, RUN, SAVE_GAME, LOAD_GAME, PRINT_INFO, PRINT_MAP, PRINT_LEVELS , PRINT_WAREHOUSE, PRINT_WELL,
    PRINT_WORKSHOPS, PRINT_VEHICLE, TURN, ADD_ITEM_TO_VEHICLE, CLEAR_VEHICLE, VEHICLE_GO, PRINT_MARKET_PRODUCTS;
}
